{{- if .Values.cve.adapter.enabled -}}
{{- if .Values.autoGenerateCert }}
{{- $cn := "neuvector" }}
{{- $cert := genSelfSignedCert $cn nil (list $cn) (.Values.defaultValidityPeriod | int) -}}
apiVersion: v1
kind: Secret
metadata:
  name: neuvector-registry-adapter-secret
type: Opaque
data:
  ssl-cert.key: {{ $cert.Key | toString | b64enc }}
  ssl-cert.pem: {{ $cert.Cert | toString | b64enc }}
---
{{- end }}
{{- end }}
