name: Publish Charts on tagging

on:
  push:
    tags: 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      TAG: ${{ github.ref_name }}
    steps:
      - uses: actions/checkout@v3
      - name: Install helm
        run: |
          curl -sSL https://get.helm.sh/helm-v3.16.2-linux-amd64.tar.gz -O helm.tar.gz
          echo "9318379b847e333460d33d291d4c088156299a26cd93d570a7f5d0c36e50b5bb  helm.tar.gz" | sha256sum --check
          tar zxvf helm.tar.gz
          cp linux-amd64/helm /usr/local/bin/helm
      - name: Publish Helm charts
        run: |
          CHARTS_TMP_DIR=$(mktemp -d)
          helm lint charts/core charts/crd charts/monitor
          helm package charts/core charts/crd charts/monitor --destination ${CHARTS_TMP_DIR} --version ${TAG#v}
          git clone "https://x-access-token:${{ secrets.HELM_PUBLISHER_TOKEN }}@github.com/${{ github.event.repository.owner }}/${{ github.event.repository.name }}" repo
          cd repo/
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git remote set-url origin "https://x-access-token:${{ secrets.HELM_PUBLISHER_TOKEN }}@github.com/${{ github.event.repository.owner }}/${{ github.event.repository.name }}"
          git checkout gh-pages
          if [[ -f "index.yaml" ]]; then
            FLAGS="--merge index.yaml"
          fi
          helm repo index ${CHARTS_TMP_DIR} --url https://${{ github.event.repository.owner }}.github.io/${{ github.event.repository.name }} ${FLAGS}
          mv -f ${CHARTS_TMP_DIR}/*.tgz ./
          mv -f ${CHARTS_TMP_DIR}/index.yaml ./index.yaml

          git add .
          git commit -m "Publish ${{ github.ref_name }}"
          git push origin gh-pages
